### ISSUE TITLE
Check on code presence in a value set must take active flag into account

### ISSUE THREAD

**Issue by kruzikh** [ehn-dcc-development/eu-dcc-business-rules#25]
Value sets could include entries which have attribute/element "active" = false
Business rules should handle inactive entries in a way appropriate to the certificate type. In practice, this might happen mainly in case of the RAT list value set. So the business logic should check if the code is active or if it was active at the moment when the certificate was issued.

**Comment by dslmeinte** [comment]
Seems to me that a generalised interpretation of issue #26 amounts to the same.

**Comment by kruzikh** [comment]
See my comment to #26 . I think this is a separate issue.

**Comment by dslmeinte** [comment]
The EU DCC Validation Rules framework effectively stipulates that value sets end up in a “compressed” form in `externalParameters.valueSets` (see Appendix B), with per value set an array of strings: the IDs of the value set entries. So, the `active` flag is not inspectable at all, as that information is erased prior to evaluation.
