### ISSUE TITLE
Is there a newer version of EU DCC Validation Rules document?

### ISSUE THREAD

**Issue by AntonioQOAtos** [ehn-dcc-development/eu-dcc-business-rules#62]
The document in the readme is the 1.0.0 that not have the appendix B schema updated. Is there a new version of this document?

**Comment by dslmeinte** [comment]
Some work has been done on a version 1.1.0, but that's not finished and approved yet. Because of holidays I can't say much about the timeframe for that, unfortunately.

**Comment by AntonioQOAtos** [comment]
ok thank you.

**Comment by dslmeinte** [comment]
v1.1 of the Validation Rules document is published [here](https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf). No updates to this version are planned.
