### ISSUE TITLE
Any work to publish package on Maven Central ?

### ISSUE THREAD

**Issue by dagdelenmustafa** [ehn-dcc-development/eu-dcc-business-rules#79]
As you mention [here](https://github.com/ehn-dcc-development/dgc-business-rules/blob/1886bcad0423b5e0a139405575f65ac380c0f9c0/documentation/implementations.md#jvm), we have to modify our **settings.xml** file to be able to use Github packages. But I don't want to use this kotlin package in this way. That's why I wonder that do you have some future plan to publish this package on maven central ? @dslmeinte

**Comment by dslmeinte** [comment]
Apologies @dagdelenmustafa : your issue slipped through. It wasn't my intention to let you go unanswered.

The simple answer is: would be good to have this, but haven't found any time yet to get it working. (It's a bit trickier than e.g. publishing an NPM package.) I reopened this issue, as it's a good reminder.

**Comment by dagdelenmustafa** [comment]
Hi @dslmeinte,

No problem at all and thanks for your reply. I look forward to new updates.

**Comment by dslmeinte** [comment]
Closed per PR #124
