### ISSUE TITLE
plusTime does not handle timezone changes

### ISSUE THREAD

**Issue by M-Wong** [ehn-dcc-development/eu-dcc-business-rules#8]
The plusTime operator parses a datetime string with the ISO8601 `ISO_OFFSET_DATE_TIME` formatter. When calculating the final datetime in the `JsonDateTime.plusTime()` method, this might cause issues when the `amount` operand leads to a timezone change due to daylight savings time.
Consider this rule:
```
{
  "<=": [
    {
      "plusTime": [
        {
          "var": "external.validationClock"
        },
        0,
        "day"
      ]
    },
    {
      "plusTime": [
        {
          "var": "payload.r.0.fr"
        },
        179,
        "day"
      ]
    }
  ]
}
```

Let's say `fr` is `2021-06-09T12:00:00+0200` and this certificate is verified (with the above rule) with a validation clock of `2021-12-05T12:00:00+0100`.

The JsonDateTime class will parse `fr` with the UTC+2 timezone, but when `plusTime` is called with an amount of 179 days, it will not adjust the timezone. This is a rare edge case, limited to only a short time window, but I still think it's important to be aware of this.

**Comment by dslmeinte** [comment]
Good catch @M-Wong : I was already waiting for someone to pick up on this :)

I'm leaving this issue open. AFAICS, this is more a policy/definition issue than it is a technical one: what does “+ 179 days” mean _exactly_, especially in the presence of DST transitions. I've raised the issue elsewhere as well. Technically, any criterion would still have to be expressed in terms of date times with timezone offset - at least I think so.

**Comment by dslmeinte** [comment]
Given that business rules are essentially defunct now, I'm closing this issue as a result.
